# Generated by Django 4.2.23 on 2025-11-28 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=64)),
                ('user_avatar', models.TextField()),
                ('app_name', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('vip_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact_ad', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
