# Generated by Django 4.2.23 on 2025-11-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAPTCHA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_ad', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
