# Generated by Django 4.1.6 on 2025-11-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_captcha_alter_userinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('rest_count', models.IntegerField(default=20)),
                ('app_name', models.CharField(max_length=10)),
            ],
        ),
    ]
